#netsession.o:netsession.cpp netsession.h
#	cc -std=gnu++0x -c -g netsession.cpp

#application.o:application.cpp application.h
#	cc -std=gnu++0x -c -g application.cpp

#clean:
#	rm -f *.o

net.a:netsession.cpp netsession.h application.cpp application.h reactorcore.cpp reactorcore.h
	ar rc libnet.a


